### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ganapathi12**
added link to  CONTRIBUTING.md file in readme

## 🚀 Description

updated a link to  CONTRIBUTING.md file in readme.

## 📄 Motivation and Context

it makes your readme perfect and easy for people to find  CONTRIBUTING.md file.

## 📦 Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [x] My code follows the code style of this project(Do your best to follow code styles. If none apply just skip this).
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ganapathi12** [comment]
i see this repository is ineligible to participate in hacktoberfest(Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.) could you please add the following topic to your repository so that it is eligible for hacktoberfest!

**Comment by dmcfaddengalway** [comment]
Updated @ganapathi12

**Comment by ganapathi12** [comment]
No,it's still shows the same and I couldn't find any hacktober fest label in repository! Please add hacktober fest label in about section(where you have reactjs,frontend,webapp labels there you need to have hacktober fest label) in this repository @dmcfaddengalway

**Comment by Tobi406** [comment]
@jmprathab is the only one that can add such a label as far as I know

**Comment by jmprathab** [comment]
> @jmprathab is the only one that can add such a label as far as I know

Done.

**Pull request merged**
